#!/bin/bash

if [ $# -ne 1 ];
then
  echo "Usage: $0 branch -> Creates all of the components for a new branch."
  echo " eg: $0 10.x -> Creates 10.x-stable, 10.x-testing, and 10.x-unstable"
  exit 1
fi

branch=$1

for comp in stable testing unstable; do
  echo "Creating repo $branch-$comp"
  aptly -config=./aptly.conf repo create -comment="$branch $comp packages" -distribution="$branch" -component=$comp $branch-$comp
done

./create-es-mirror $branch 7.10.2 7.10.3
./create-os-mirror $branch 1.3.3 2.0.0
./drop-mirror es $branch testing
./drop-mirror os $branch testing
./drop-mirror es $branch unstable
./drop-mirror os $branch unstable
./update-mirror $branch stable es
./update-mirror $branch stable os


maj=`echo $branch | cut -c -2`
source_branch="$(($maj-1))"
for package in ffmpeg-dist opensearch-dist tobira
do
  name=`./list-repo-package-versions $source_branch.x | grep $package | head -n 1 | tr -d ' '`
  version=`echo $name | cut -f 2 -d "_"`
  ./copy-package $package $version $source_branch.x $branch stable stable
done
echo "Copied latest ffmpeg-dist, opensearch-dist, and tobira"

echo "Done"
