#!/bin/bash

if [ $# -ne 4 ];
then
  echo "Usage: $0 opencast_branch component package_name version -> Removes a package from a component."
  echo " eg: $0 9.x stable ffmpeg 4.3.0-1 -> Removes all ffmpeg 4.3.0-1 packages from stable, if they exist."
  exit 1
fi

ocBranch=$1
ocMajor=${ocBranch::1}
ocComponent=$2

packageName=$3
packageVersion=$4

repo="$ocBranch-$ocComponent"

aptly -config=./aptly.conf repo remove $repo "Name (% $packageName*), \$Version (=$packageVersion)"

