#!/bin/bash

if [ $# -lt 1 -o $# -gt 3 ];
then
  echo "Usage: $0 branch [storage] [keyId] -> Creates a snapshot all of the components for the branch, and publishes them with the right Elastic/Opensearch version into a given storage.  Optionally set the gpg key ID to use for signing."
  echo " eg: $0 10.x -> Publishes 10.x to the default storage with the default key"
  echo " eg: $0 10.x s3 -> Publishes 10.x to the s3 storage, with the default key"
  echo " eg: $0 10.x other abc123 -> Publishes 10.x signed by abc123 to the 'other' storage"
  echo "NOTE: If you are seeing errors about a missing snapshot named \$date-\$branch-(os|es), try running update-mirror.  This script is assuming that update-mirror has been run *today*."
  exit 1
fi

today=`date --utc +%FT%H%M%SZ`
branch=$1
target="s3:s3:"
if [ $# -ge 2 ]; then
  target="$2"
fi
keyId="3259FFB3967266533FCD4B249A7EA8E5B3820B26"
if [ $# -ge 3 ]; then
  keyId="$3"
fi

for comp in stable testing unstable; do
  #What should today's snapshot for this branch+component be called
  snapshot="$today-$branch-$comp"
  snapshot_oc="$snapshot-oc"
  
  #Create a new snapshot of the OC binaries
  if [ -n "`aptly -config=./aptly.conf snapshot list -raw | grep $snapshot-oc`" ]; then
    echo "Deleting pre-existing snapshot $snapshot and $snapshot-oc"
    aptly -config=./aptly.conf snapshot drop $snapshot
    aptly -config=./aptly.conf snapshot drop $snapshot-oc
  fi
  aptly -config=./aptly.conf snapshot create $snapshot_oc from repo $branch-$comp

  #Figure out which ES snapshot to use, if any are applicable
  snapshot_es=`aptly -config=./aptly.conf snapshot list -raw | grep $branch-$comp-es | sort -n | tail -n 1`
  snapshot_os=`aptly -config=./aptly.conf snapshot list -raw | grep $branch-$comp-os | sort -n | tail -n 1`

  snapshot_tobira=`aptly -config=./aptly.conf snapshot list -raw | grep tobira | sort -n | tail -n 1`

  #Merge them into a single snapshot so it's publishable
  if [ "stable" == "$comp" ]; then
    aptly -config=./aptly.conf snapshot merge $snapshot $snapshot_oc $snapshot_es $snapshot_os $snapshot_tobira
  else
    aptly -config=./aptly.conf snapshot merge $snapshot $snapshot_oc $snapshot_es $snapshot_os
  fi
done

if [ -z "`aptly -config=./aptly.conf publish list -raw | grep "$target" | grep $branch`" ]; then
  #Publish the new branch
  aptly -config=./aptly.conf publish snapshot -gpg-key="$keyId" -component=stable,testing,unstable -distribution=$branch $today-$branch-stable $today-$branch-testing $today-$branch-unstable $target
else
  for comp in stable testing unstable; do
    aptly -config=./aptly.conf publish switch -gpg-key="$keyId" -component=$comp $branch $target $today-$branch-$comp
  done
fi
