#!/bin/bash

if [ $# -ne 2 ]; then
  echo "Usage: $0 branch s3_target: Remove all non-published snapshots from storage (but not S3!)"
  exit 1
fi

branch=$1
storage=$2

publishedSnapshots=`./list-published-package-versions $branch $storage | grep Snapshot | sed 's/Snapshot \(.*\):/\1\\\|/g' | tr -d '\n' | cut -f 1-3 -d '\'`

./list-snapshots $branch | grep -Ev '\-es|\-os' | grep -v "$publishedSnapshots" | cut -f 1-3 -d '-' | uniq | while read line
do
       ./drop-snapshots $1 oc $line
done
