#!/bin/bash

if [ $# -ne 4 ];
then
  echo "Usage: $0 opencast_branch source_component dest_component version -> Copies a package from a source component to a dest component."
  echo " eg: $0 9.x testing stable 9.0-1 -> Copies all Opencast 9 9.0-1 packages from testing to stable, if they exist."
  exit 1
fi

ocBranch=$1
ocMajor=${ocBranch::1}
ocSrcComponent=$2
ocDestComponent=$3

packageVersion=$4

srcRepo="$ocBranch-$ocSrcComponent"
destRepo="$ocBranch-$ocDestComponent"

aptly -config=./aptly.conf repo copy $srcRepo $destRepo "Name (% opencast-$ocMajor*), \$Version (=$packageVersion)"

