#!/bin/bash

if [ $# -ne 5 ];
then
  echo "Usage: $0 opencast_branch source_component dest_component package_name version -> Copies a package from a source component to a dest component."
  echo " eg: $0 9.x testing stable ffmpeg-dist 4.3.0-1 -> Copies all ffmpeg-dist 4.3.0-1 packages from testing to stable, if they exist."
  exit 1
fi

ocBranch=$1
ocSrcComponent=$2
ocDestComponent=$3

packageName=$4
packageVersion=$5

srcRepo="$ocBranch-$ocSrcComponent"
destRepo="$ocBranch-$ocDestComponent"

aptly -config=./aptly.conf repo copy $srcRepo $destRepo "Name (% $packageName*), \$Version (=$packageVersion)"

