#!/bin/bash

if [ $# -ne 3 ];
then
  echo "Usage: $0 opencast_branch component version -> Removes a package from a component."
  echo " eg: $0 9.x stable 9.0-1 -> Removes all Opencast 9 9.0-1 packages from stable, if they exist."
  exit 1
fi

ocBranch=$1
ocMajor=${ocBranch::1}
ocComponent=$2

packageVersion=$3

repo="$ocBranch-$ocComponent"

aptly -config=./aptly.conf repo remove $repo "Name (% opencast-$ocMajor*), \$Version (=$packageVersion)"

