#!/bin/bash

if [ $# -ne 4 ];
then
  echo "Usage: $0 opencast_branch component min_version max_version -> Creates a mirror of the Elasticsearch repository with with the right version requirements for Opencast's branch."
  echo " eg: $0 9.x stable 7.9.2 7.10.0 -> Creates an 'es-9.x-stable' mirror, restricted to Elasticsearch >= 7.9.2, and < 7.10.0"
  exit 1
fi

ocBranch=$1
component=$2
minVersion=$3
maxVersion=$4
esBranch="`echo $minVersion | cut -c 1`"

mirrorName="es-$ocBranch-$component"
if [ -n "`aptly -config=./aptly.conf mirror list -raw | grep $mirrorName`" ]; then
  aptly -config=./aptly.conf -architectures=amd64 mirror edit -keyring=./trusted.gpg -filter="elasticsearch-oss (>=$minVersion) {amd64}, \$Version (<<$maxVersion)" $mirrorName
else
  echo "Mirror $mirrorName doesn't exist!"
fi
