#!/bin/bash

if [ $# -ne 1 ];
then
  echo "Usage: $0 branch -> Lists the packages published by all of the snapshots published as this branch."
  echo " eg: $0 10.x -> Lists the packages in the currently published stable, testing, and unstable snapshots."
  exit 1
fi

aptly -config=./aptly.conf repo list -raw | grep $1 | while read line
do
  echo -e "\nRepo $line:"
  aptly -config=./aptly.conf repo show -with-packages $line
done
